name: Mend CLI SCA NPM Scan

on:
  push:
    branches: [ master* ]
  pull_request:
    branches: [ master* ]

jobs:
  Build:
    runs-on: ubuntu-latest        
      - name: Mend CLI Scan
        env:
          MEND_EMAIL: ${{secrets.EMAIL}}
          MEND_USER_KEY: ${{secrets.USERKEY}}
          MEND_URL: https://saas.eu.mend.io
        run: |
          echo Downloading Mend CLI
          curl https://downloads.mend.io/production/unified/latest/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
          mend sca -u
